version: '3.8'
services:
  musiclover:
    image: leonautilus/musiclover:latest
    container_name: musiclover
    restart: always
    ports:
      - "5151:5151"
    volumes:
      - ./config.yaml:/app/config.yaml  # 配置文件映射
      - ./logs:/app/logs  # 日志目录映射
      - ./downloads:/app/downloads  # 下载目录映射
    environment:
      - TZ=Asia/Shanghai  # 设置时区
